---
title: Safe
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:title/"
    featured-image: ''
    posts:
    -
    -
    -
email: mdlorey@gmail.com
description: A globally accessible and anonymous blockchain
baseurl: ""
url: https://safesystem.io
author:
  name: Safe
  email: info@safecoin.com
  uri: https://safesystem.io/
  bio:
  facebook: https://www.facebook.com/safecoin/
  twitter: safecoinofficial
  linkedin: https://www.linkedin.com/company/25052505/
  gplus:
  youtube: https://www.youtube.com/channel/UCQ0v_lUnZHIKUQUXJzfgqOg
links:
  bitcointalk: https://bitcointalk.org/index.php?topic=2047435.0
  blog: https://blog.safesystem.io/
  facebook: https://www.facebook.com/safecoin/
  linkedin: https://www.linkedin.com/company/25052505/
  forum: https://forum.safesystem.io/
  github: https://github.com/SafecashOfficial
  medium: https://medium.com/safecoin
  reddit: https://www.reddit.com/r/SafeSys/
  discord: https://discord.gg/CEbKY9w
  slack: https://slackinvite.safesystem.io/
  telegram: https://t.me/safecoin
  twitter: https://twitter.com/safecoinofficial
  youtube: https://www.youtube.com/channel/UCQ0v_lUnZHIKUQUXJzfgqOg
  whitepaper: /assets/Safe%20White%20Paper.pdf
wallets:
  swing: https://github.com/SafecashOfficial/safecoin-swing-wallet-ui/releases
  arisafe: https://github.com/SafecashOfficial/arisafe/releases
future: true
show_drafts: true
lsi: false
permalink: pretty
paginate: 6
paginate_path: "/blog/page:num/"
excerpt_separator:
markdown: kramdown
cloudinary:
  cloud_name: dw4i3sw5c
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"
gems:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-sass-converter
- jekyll-multiple-languages-plugin
exclude:
- _dev
- bower.json
- .env.json
- Gemfile
- Gemfile.lock
- gulpfile.js
- LICENSE.md
- node_modules
- package.json
- README.md
- vendor
- old-homepage.html

languages: ["en"]
exclude_from_localizations: ["assets"]
